apiVersion: v1
kind: Service
metadata:
  name: coll-f54bce0491cf44e2a552d2379f820f5a-srv
spec:
  selector:
    app: coll-f54bce0491cf44e2a552d2379f820f5a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP